name: Release Workflow

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - fix/*
      - master

jobs:
  release_job:
    name: Release Job
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    inputs:
      branch: ${{ github.ref }}
      repo: go-practises
      user: gaurav04
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Semantic Release
        uses: Nightapes/go-semantic-release-action@v2.0.0
          
      - name: Release Candidate
        if: startsWith(inputs.branch, 'refs/heads/feature/') || startsWith(inputs.branch, 'refs/heads/bugfix/') || startsWith(inputs.branch, 'refs/heads/fix/')
        env:
          RELEASE_BRANCH: rc
        run: |
          echo "commitFormat: conventional" > .release.yml
          echo "branch:" >> .release.yml
          echo "  ${{ inputs.branch }}: ${{ env.RELEASE_BRANCH }}" >> .release.yml
          echo "release: 'github'" >> .release.yml
          echo "github:" >> .release.yml
          echo "  repo: ${{ inputs.repo }}" >> .release.yml
          echo "  user: ${{ inputs.user }}" >> .release.yml
          VERSION=$(./semantic-release next | tr -d '\r\n')
          echo "VERSION = v${VERSION}" >> $GITHUB_ENV
          ./semantic-release release

      - name: Release
        if: inputs.branch == 'refs/heads/master'
        env:
          RELEASE_BRANCH: release
        run: |
          echo "commitFormat: conventional" > .release.yml
          echo "branch:" >> .release.yml
          echo "  master: ${{ env.RELEASE_BRANCH }}" >> .release.yml
          echo "release: 'github'" >> .release.yml
          echo "github:" >> .release.yml
          echo "  repo: ${{ inputs.repo }}" >> .release.yml
          echo "  user: ${{ inputs.user }}" >> .release.yml
          VERSION=$(./semantic-release next | tr -d '\r\n')
          echo "VERSION = v${VERSION}" >> $GITHUB_ENV
          ./semantic-release release
