name: Semantic Release

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'fix/*'
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Semantic Release
        run: |
          curl -SL https://github.com/Nightapes/go-semantic-release/releases/download/v2.1.1/go-semantic-release.linux_x86_64.zip -o go-semantic-release.linux_x86_64.zip
          unzip go-semantic-release.linux_x86_64.zip
          chmod +x ./go-semantic-release.linux_x86_64
          mv go-semantic-release.linux_x86_64 semantic-release
        
      - name: Validate and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="X.X.X"
          
          if [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
            # use rc for non-master branches
            release_kind="rc"
          else
            # use release for master branch
            release_kind="release"
          fi
          
          last=$(./semantic-release last)
          next=$(./semantic-release next)

          # do not build unless changes were detected
          if [ "$next" != "$last" ]; then
            VERSION="v$next"
            echo Releasing VERSION=$VERSION using $release_kind kind
            ./semantic-release ${release_kind}
          else
            echo "No change detected between $last and $next"
          fi
